name = "worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"
# The "modules" upload format is required for all projects that export a Durable Object class.
upload.format = "modules"
upload.main = "./shim.mjs"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]
